#!/system/bin/sh
log -p i -t start "******** Welcome to SOSP-OS Project **********";
log -p i -t start "****   *****   ****    *****     *****  ****  ";
log -p i -t start "*      *   *   *       *   *     *   *  *     ";
log -p i -t start "****   *   *   ****    *****  ** *   *  ****  ";
log -p i -t start "   *   *   *      *    *         *   *     *  ";
log -p i -t start "****   *****   ****    *         *****  ****  ";
log -p i -t start "************ Android 10.0 ********************";
